### ISSUE TITLE
Plot price trajectories

### ISSUE THREAD

**Issue by Bouncner** [hpi-epic/pricing_competition_simulation#6]
Currently, we create a trajectory output CSV with which we plot the trajectory graphs.

To improve the user's understanding of the notebooks, let's skip the CSV and plot directly.

**Comment by Bouncner** [comment]
Tom, please take a look `step plots` in matplotlib for the visualization.

Example: https://matplotlib.org/gallery/lines_bars_and_markers/step_demo.html#sphx-glr-gallery-lines-bars-and-markers-step-demo-py

**Comment by tomschw** [comment]
As I understand it the plot should be created directly in the market_simulation notebook? Wouldn't it be better to have every relevant plot in the same notebook?

**Comment by Bouncner** [comment]
Matter of taste. If I understand you correctly, you'd like to see all plots in one single notebook?

I would disagree. This would confuse the learning processes with "external / synthetic" market processes(/data).

**Comment by Bouncner** [comment]
Ping @tomschw .

**Comment by tomschw** [comment]
I also think your version is better, it was just that I misunderstood what you want when we talked about it and just wanted to be sure. I'll do it in the pertaining notebook, but first I will work on #5 which should be easy to solve.
